Second commit
tenantcloud/ansible-role-dashboard pull request #1
Opened 2020-01-27 15:47 UTC by odebretseni

2020-01-28 07:55 UTC, vikfedkiv commented on tasks/change-env-file.yml
> +
Add CDN_URL=S3_AWS_URL=https://home.{{ work_domain }}:9002/local

2020-01-28 07:55 UTC, vikfedkiv commented on tasks/create-minio-backet.yml
> +- name: Create s3 local backet
Bucket "local" is present in docker image on ECR

2020-01-28 09:15 UTC, BrunIF requested changes

2020-01-28 09:15 UTC, BrunIF commented on meta/main.yml
> +        - "Catalina"
Mac OS version should be a number

2020-01-28 09:15 UTC, BrunIF commented on tasks/change-env-file.yml
> +    line: 'SOCKETIO_URL=https://home.{{ work_domain }}'
What happens if you raise a different project?  Keller

2020-01-28 09:15 UTC, BrunIF commented on tasks/change-env-file.yml
> +- name: Add DB_ACTIVITY_LOG_HOST
needless. It is deprecated now.

2020-01-28 09:15 UTC, BrunIF commented on tasks/change-env-file.yml
> +- name: Add CONVERTER_DRIVER
You install LibreOffice, or get it in a container?

2020-01-28 09:15 UTC, BrunIF commented on tasks/copy-idea-settings.yml
> +  become: false
By default `become` is false. 
Don`t run ansible playbook with key `-k -K`

2020-01-28 09:15 UTC, BrunIF commented on tasks/copy-pre-commit-script.yml
> +#- name: pre-commit copy
Delete old code

2020-01-28 09:15 UTC, BrunIF commented on tasks/create-minio-backet.yml
> +---
needless. Use our docker image. 
Create bucket with `docker exec .....`

2020-01-28 09:15 UTC, BrunIF commented on tasks/create-work-folder.yml
> +  become: false
needless.
Review all files

2020-01-28 09:15 UTC, BrunIF commented on tasks/create-work-folder.yml
> +---
It is not logical. You create directory in one place, and work with them in other tasks

2020-01-28 09:15 UTC, BrunIF commented on tasks/create_db_mysql.yml
> +  command: echo 'export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"' >> ~/.zshrc
MySQL version to `default/main.yml`
What happend if we will use MySQL 8?

2020-01-28 09:15 UTC, BrunIF commented on tasks/docker-compose.yml
> +---
This is an old configuration. Please review. 
I don't understand what do you do.

2020-01-28 09:15 UTC, BrunIF commented on tasks/git-clone.yml
> +---
It is not logical.
Please do next.
Clone -> Configure `.env` -> Setup project

2020-01-28 09:15 UTC, BrunIF commented on tasks/main.yml
> +- include: run_dnsmasq.yml
Configure?

2020-01-28 09:15 UTC, BrunIF commented on tasks/main.yml
> +- include: change-env-file.yml
Configure?

2020-01-28 09:15 UTC, BrunIF commented on tasks/main.yml
> +- include: change-nginx-settings.yml
Configure?

2020-01-28 09:15 UTC, BrunIF commented on templates/ext-xdebug.ini
> +xdebug.remote_host=localhost
Better will be use IP address

2020-01-28 09:15 UTC, BrunIF commented on templates/home.kellermanagement.dev.conf
> +    location /socket.io/ {
deprecated

2020-01-28 09:15 UTC, BrunIF commented on templates/home.kellermanagement.dev.conf
> +    access_log /usr/local/var/log/nginx/home.km.access.log;
`home.km`?

2020-01-28 09:15 UTC, BrunIF commented on templates/home.tenantcloud.dev.conf
> +    location /socket.io/ {
deprecated

2020-01-28 09:15 UTC, BrunIF commented on templates/home.tenantcloud.dev.conf
> +server {
templates/home.conf

2020-01-28 09:15 UTC, BrunIF commented on templates/mysql.sh
> +#!/bin/bash
Better practice https://docs.ansible.com/ansible/latest/modules/mysql_db_module.html#mysql-db-module

2020-01-28 09:15 UTC, BrunIF commented on templates/yarn.sh
> +#!/bin/bash
https://docs.ansible.com/ansible/latest/modules/npm_module.html

2020-01-28 09:15 UTC, BrunIF commented on templates/yarn.sh
> +cp tests/Protractor/protractorEnvironment.example.js tests/Protractor/protractorEnvironment.js
This is another task

2020-01-28 09:15 UTC, BrunIF commented on vars/main.yml
> +dashboard_git:
`dashboard_git: ""`

2020-01-28 12:30 UTC, odebretseni commented on tasks/change-env-file.yml
> +- name: Add CONVERTER_DRIVER
install separately

2020-01-28 12:46 UTC, odebretseni commented on templates/home.tenantcloud.dev.conf
> +server {
and keller?

2020-01-31 11:54 UTC, BrunIF approved these changes

2020-01-31 11:54 UTC, merged