php version changed to 7.4
tenantcloud/ansible-role-dashboard pull request #13
Opened 2020-05-11 19:10 UTC by odebretseni

2020-05-12 06:40 UTC, BrunIF requested changes

2020-05-12 06:40 UTC, BrunIF commented on tasks/configure-php-settings.yml
> +    path: /usr/local/etc/php/7.4/php.ini
давай зробимо для будь якої версії. Версія по замовчуванню хай буде 7.4, але щоб можна було для інших проектів вказати інше PHP. У нас багато проектів на php7.1

2020-05-12 06:40 UTC, BrunIF commented on tasks/configure-php-settings.yml
> +    path: /usr/local/etc/php/7.4/php.ini
те саме. І треба по коду перевірити де є згадки і поправити

2020-06-04 14:19 UTC, BrunIF requested changes

2020-06-04 14:19 UTC, BrunIF commented on templates/vault_functions.sh.j2
> +#!/usr/bin/env bash
В цьому файлі ти ж не будеш нічого змінювати. Тому це не шаблон, а просто файл. Ти його копіюєш.

2020-06-09 07:41 UTC, BrunIF requested changes

2020-06-09 07:41 UTC, BrunIF commented on files/vault_functions.sh.j2
> +#!/usr/bin/env bash
Якщо це не шаблон, то не потрібно додавати розширення `j2`. Це не файл з шаблоном jinja 2

2020-06-09 07:41 UTC, BrunIF commented on templates/vault-configuration.j2
> +export VAULT_ADDR=
Якщо це шаблон, то чому немає змінних?

2020-06-15 14:23 UTC, BrunIF requested changes

2020-06-15 14:23 UTC, BrunIF commented on README.md
> +        php_release:
також додати змінні у defaults і прикладі yml не потрібно буде описувати всі змінні які описані у **Role Variables**, а тільки тоді, коли буде потреба їх перевизначити.

2020-06-15 14:23 UTC, BrunIF commented on files/vault-configuration
> +export VAULT_PASSWORD=
а нащо цього? Якщо при ініціалізації створюється файл і заповнюється. Не потрібно цього.

2020-06-15 14:23 UTC, BrunIF commented on files/vault_functions.sh
> +#!/usr/bin/env bash
Ці функції будуть в іншому місці. Не потрібно засмічувати роль.

2020-06-15 14:23 UTC, BrunIF commented on tasks/configure-vault-settings.yml
> +    mode: a+x
буде окремий репозиторій функції. В ролі не буде цього файлу.

2020-06-15 14:23 UTC, BrunIF commented on tasks/configure-vault-settings.yml
> +  template: src=post-checkout.j2 dest=$HOME/{{ work_dir }}/home.{{ work_domain }}/.git/hooks/post-checkout mode=a+x
це у проекті, так як і перевірка php-cs-fix

2020-06-15 14:23 UTC, BrunIF commented on templates/post-checkout.j2
> +vault_get "$PROJECT_NAME/dev/$VAULT_BRANCH" .env
це також у проект.

2020-06-15 19:38 UTC, odebretseni commented on files/vault-configuration
> +export VAULT_PASSWORD=
тому що я роблю source zshrc де прописані шляхі до всіх цих файлів, до моменту ініціалізіції його не існує тоді при source zshrc ансіблом буде помилка.

2020-06-26 09:22 UTC, BrunIF requested changes

2020-06-26 09:22 UTC, BrunIF commented on files/vault-configuration
> +export VAULT_PASSWORD=
тоді не потрібно його прописувати у .zshrc якщо його ще немає. Може й потреби не буде. 
подбумай. 
На крайній випадок створюй просто порожній файл.

2020-06-26 10:42 UTC, odebretseni commented on files/vault-configuration
> +export VAULT_PASSWORD=
так я не можу передбачити чи буде потреба чи не буде, це ж не моє рішення...якщо я звідси заберу це тоді десь це треба поставити...

2020-07-10 08:30 UTC, BrunIF requested changes

2020-07-10 08:30 UTC, BrunIF commented on tasks/configure-vault-settings.yml
> +  changed_when: false
Може вже варто переробити через tcctl ?

2020-07-10 09:09 UTC, odebretseni commented on tasks/configure-vault-settings.yml
> +  changed_when: false
в нас це взагалі тут не потрібно по логіці, тому що флов напевно буде іншим:
1. Ансіблом ми все ставимо як і ставили
2. Далі чи треба додати в ансібл інсталяцію bcl зі всіма слідуючими налаштуваннями,  або це буде робити дев по інструкції яка є.
3. В папці проекту буде цей файл BUILD - по якому інсталити необхідну версію всіх пакетів з кодом
4. Ну і далі є команди якими можно конфіжити і файл зкредами і запускати хук (якій також вже є в проекті)

2020-07-29 07:30 UTC, BrunIF approved these changes

2020-07-29 07:30 UTC, merged