Create Ansible-lint, Yamllint
tenantcloud/ansible-role-dashboard pull request #15
Opened 2020-10-02 08:06 UTC by odebretseni

2020-10-02 09:19 UTC, BrunIF requested changes

2020-10-02 09:19 UTC, BrunIF commented on tasks/configure-dashboard.yml
> +    src: '$HOME/{{ work_dir }}/home.{{ work_domain }}/docs/installation/git-hooks/pre-commit'   # yamllint disable-line rule:line-length
Зроби через змінні. 
Створи змінну яка складається з змінних.

2020-10-02 09:19 UTC, BrunIF commented on tasks/configure-dashboard.yml
> +    mode: 0644
нащо постійно задавати права? Воно б мало брати маску з системи.

2020-10-02 09:22 UTC, odebretseni commented on tasks/configure-dashboard.yml
> +    mode: 0644
до кожного рядка де є операція з файлом таке вимагає ansible-lint, приклад з промо де нема заданих прав:
![image](https://user-images.githubusercontent.com/50202839/94908102-e30a0180-04a9-11eb-9119-f90acb98d5de.png)

2020-10-02 09:25 UTC, odebretseni commented on tasks/configure-dashboard.yml
> +    src: '$HOME/{{ work_dir }}/home.{{ work_domain }}/docs/installation/git-hooks/pre-commit'   # yamllint disable-line rule:line-length
можно - я так пробував - але на мою думку це потім ускладнює розуміння де які змінні за що відповідають...

2020-10-02 10:52 UTC, BrunIF commented on tasks/configure-dashboard.yml
> +    src: '$HOME/{{ work_dir }}/home.{{ work_domain }}/docs/installation/git-hooks/pre-commit'   # yamllint disable-line rule:line-length
наразі тут солянка. Читається не дуже, та ще й валідація не проходить. 
Причому по коді воно використовується не раз, тому можна зробити одну змінну і нею користуватися.

2020-10-06 09:01 UTC, vikfedkiv approved these changes

2020-10-06 09:34 UTC, BrunIF approved these changes

2020-10-06 09:36 UTC, merged