added check for the existence of modules imagick, xdebug
tenantcloud/ansible-role-dashboard pull request #4
Opened 2020-02-04 09:26 UTC by odebretseni

2020-02-05 08:01 UTC, BrunIF requested changes

2020-02-05 08:01 UTC, BrunIF commented on tasks/configure-php-settings.yml
> +    path: /usr/local/lib/php/pecl/20160303/imagick.so
maybe try use variable? `20160303`

2020-02-05 08:01 UTC, BrunIF commented on tasks/configure-php-settings.yml
> +    path: /usr/local/lib/php/pecl/20160303/xdebug.so
also?

2020-02-05 08:01 UTC, BrunIF commented on tasks/configure-php-settings.yml
>      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
Try to use `args` and run from PECL directory

2020-02-05 08:01 UTC, BrunIF commented on tasks/deploy-dashboard.yml
>      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
`args` run with bash

2020-02-05 10:54 UTC, odebretseni commented on tasks/deploy-dashboard.yml
>      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
[WARNING]: As of Ansible 2.4, the parameter 'executable' is no longer supported with the 'command' module. Not using '/bin/bash'.

2020-02-06 15:15 UTC, BrunIF requested changes

2020-02-06 15:15 UTC, BrunIF commented on templates/horizon.ini.j2
> +command=/usr/local/opt/php@7.1/bin/php /Users/{{ work_user }}/{{ work_dir }}/{{ dashboard_dir }}/artisan horizon
if will use 7.4 PHP ?

2020-02-06 15:15 UTC, BrunIF commented on tasks/configure-php-settings.yml
>    command: brew services start php@7.1
Version in defaults

2020-02-07 07:36 UTC, BrunIF requested changes

2020-02-07 07:36 UTC, BrunIF commented on templates/info.txt.j2
> + - npm run test //carma-test
Change like a Promo

2020-02-07 09:19 UTC, BrunIF approved these changes

2020-02-07 09:19 UTC, merged